# Setup
title:        "Privacy Bible"
tagline:      example
baseurl:      "https://blog.metomic.io"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

#Others
markdown: kramdown