# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Incognito
title: Incognito
email: incognito@metomic.io
description: Demystifying data ethics, privacy, and technology
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.metomic.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /main/:year/:month/:day/:title:output_ext

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

category_colors:
  Longform: '#2ECA88'
  Weekly Roundup: '#D98759'
  Explainer: '#466993'
  Opinion: '#E0AB4A'
  Company: '#58466D'
  Guests: '#57B8A6'
  Product: '#EB4967'

category_descriptions:
  Longform: "Thought pieces about data ethics and technology; what's happening right now and what it could mean for the future."
  Weekly Roundup: "A weekly update of what's happening in the data privacy sphere, that anyone can digest. Updated on Monday mornings"
  Explainer: "Short, playful explanations of complex issues and technical things that are useful to know"
  Opinion: "Commentary on recent events in technology and data privacy"
  Company: "Metomic's story; changes and growth"
  Guests: "Pieces by external authors who have different knowledge and expertise to us at Metomic"
  Product: "What we've built, and what we learned in the process"

# Hiding a category removes it from the navbar, so posts in hidden categories still show up in "Latest" and are still accessible from permalinks
category_hidden: [
  "Weekly Roundup"
]

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

